### ISSUE TITLE
Issue with the binary execution, missing library

### ISSUE THREAD

**Issue by arsulegai** [askmish/sawtooth-poet2#45]
Path is relative and a binary is created, during execution .so file is expected by binary in relative. Ideal solution should be read from env for production, can be hardcoded for dev.

https://github.com/askmish/sawtooth-poet2/blob/7d4515b26976364d6354a86b490f8e211c91ba04/src/core/src/enclave_sgx.rs#L88

**Comment by askmish** [comment]
This was scheduled and has been fixed in build integration effort. Closing this issue.
Feel free to reach out and/or reopen this issue if still unresolved.
